#!/usr/bin/env python3
"""
Example Python script showing how the generated batch processing code might look.
This is just for demonstration - the actual code will be generated by the AI.
"""

import csv
from openbatch import BatchCollector

def example_sentiment_analysis():
    """
    Example of sentiment analysis batch processing using openbatch.
    This is the kind of code that would be generated by our Go application.
    """
    batch_file_path = "sentiment_batch.jsonl"
    collector = BatchCollector(batch_file_path=batch_file_path)
    
    instructions = """You are an expert annotator. Judge the sentiment of the user-provided comment. 
    Use the categories 'Positive', 'Neutral', and 'Negative'."""
    
    # Simulate reading from a CSV file
    sample_data = [
        {"id": "a-123", "text": "The product is absolutely fantastic!"},
        {"id": "b-456", "text": "It broke after just one week of use."},
        {"id": "c-789", "text": "The packaging was okay."}
    ]
    
    for item in sample_data:
        collector.responses.create(
            custom_id=item["id"],
            model="qwen3",  # Could be gpt-4o-mini or qwen3 depending on the API
            instructions=instructions,
            input=[{"role": "user", "content": item["text"]}]
        )
    
    print(f"Batch file '{batch_file_path}' prepared with {len(sample_data)} items.")

if __name__ == "__main__":
    example_sentiment_analysis()